sudo: required
services: 
  - docker


before_install:
  - docker build -t sakksoftware/hsse-admin-client-test -f ./client/Dockerfile.dev ./client

scripts:
  - docker run sakksoftware/hsse-admin-client-test npm test -- --coverage

after_success:
  - docker build -t sakksoftware/hsse-admin-client ./client
  - docker build -t sakksoftware/hsse-nginx ./nginx
  - docker build -t sakksoftware/hsse-server ./server
  