sudo: required
services:
  - docker

before_install:
  - docker build -t sakksoftware/hsse-admin-client-test -f ./client/Dockerfile.dev ./client

script:
  - docker run sakksoftware/hsse-admin-client-test q

after_success:
  - docker build -t sakksoftware/hsse-admin-client ./client
  - docker build -t sakksoftware/hsse-nginx ./nginx
  - docker build -t sakksoftware/hsse-server ./server
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push sakksoftware/hsse-admin-client
  - docker push sakksoftware/hsse-nginx
  - docker push sakksoftware/hsse-server