version: '3'
services:
    nginx:
      restart: always
      build:
        dockerfile: Dockerfile.dev
        context: ./nginx
      ports:
        - '3050:80'
    hsse-server:
      restart: "no"
      build: 
        context: ./server
        dockerfile: Dockerfile.dev
      volumes:
        - /app/node_modules
        - ./server:/app
      environment:
        - HSSE_ADMIN_CLIENT=hsse-admin-client
        
    hsse-admin-client:
      build:
        context: ./client
        dockerfile: Dockerfile.dev
      volumes:
        - /app/node_modules
        - ./client:/app
      environment:
        - HSSE_SERVER_HOST=hsse_server
    hsse-admin-client-test:
      build:
        context: ./client
        dockerfile: Dockerfile.dev
      volumes:
        - /app/node_modules
        - ./client:/app
      command: ["npm", "run", "test"]