version: '3'
services:
    nginx:
      restart: always
      build:
        dockerfile: Dockerfile.dev
        context: ./nginx
      ports:
        - '3050:80'
    hsse-server:
      restart: "no"
      build: 
        context: ./server
        dockerfile: Dockerfile.dev
      volumes:
        - /app/node_modules
        - ./server:/app
      environment:
        - HSSE_SES_ACCESS_KEY=AKIAJLYCLI5GYDMRIATA
        - HSSE_SES_SECRET_KEY=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
        - MONGO_URI=mongodb://sakksoftware:sakk11software@ds121282.mlab.com:21282/machealthsci-dev
        - NODE_ENV=development
        - JWT_SECRET=akfjlaksdjlasfjasdfljiasdfasfksldf
        - FRONTEND_SERVER=http://hsse-admin-client
        - BACKEND_SERVER=http://hsse-server
        - REGION=us-east-1
    hsse-admin-client:
      build:
        context: ./client
        dockerfile: Dockerfile.dev
      volumes:
        - /app/node_modules
        - ./client:/app
      environment:
        - BACKEND_SERVER=hsse_server
    hsse-admin-client-test:
      build:
        context: ./client
        dockerfile: Dockerfile.dev
      volumes:
        - /app/node_modules
        - ./client:/app
      command: ["npm", "run", "test"]